.github/workflows/pr-lint.yml

Created a `pr-lint.yml` file to create GitHub Actions which contain two jobs that check
- the branch name meets the agreed convention
- the pull request name meets the agreed convention

NIAD-824: create GitHub task to check branch and PR naming convention

---

.github/pull_request_template.md
.github/workflows/pr-lint.yml
README.md

* Add description template to all pull requests
* See how this template would look below
* Update workflow so task or hotfix branches can be named
* For example, this branch is more of a task than a feature
* I propose we leave the `NIAD-[0-9]` prefix on PR titles and branch names so we enforce that. And any branch which isn't tied to a ticket (like this one) we have the prefix something like `NIAD-0`
* Updated README
---

NIAD-0: Add description template to all pull requests.

---

src/main/java/uk/nhs/digital/nhsconnect/lab/results/model/edifact/ReferenceServiceSubject.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/model/edifact/UnstructuredAddress.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/model/edifact/ReferenceServiceSubjectTest.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/model/edifact/UnstructuredAddressTest.java

Add two new fields for SG6:
* ReferenceServiceSubject (`RFF+SSI`)
* UnstructuredAddress (`ADR`)
https://gpitbjss.atlassian.net/browse/NIAD-1023

NIAD-1023: Add SG6 segment code

---

README.md
docker-compose.lb.override.yml
nginx.conf

Ported over and adapted the docker-compose.lb.override.yml file from
the NHAIS project, along with the instructions on how to use it in
README.md
https://gpitbjss.atlassian.net/browse/NIAD-865

NIAD-865: Enable load balanced local deployments

---

Jenkinsfile

Acted on the `TODO` comments in `Jenkinsfile` and changed the relevant `echo` statements to `error` so that errors on pushing the generated Docker image and deployment to AWS ECR using Terraform will be stated in the Jenkins pipeline
https://gpitbjss.atlassian.net/browse/NIAD-827

NIAD-827: CD PR merge pipeline

---

README.md

Add documentation on how to run checkstyle, spotbugs, unit and integration tests separately and together. 
https://gpitbjss.atlassian.net/browse/NIAD-860

NIAD-860: Add Checkstyle and Spotbugs Documentation

---

src/main/java/uk/nhs/digital/nhsconnect/lab/results/inbound/queue/MeshInboundQueueService.java
src/main/resources/application.yml
src/main/resources/logback.xml

Add logging to `MeshInboundQueueService` to verify queue name and activity
https://gpitbjss.atlassian.net/browse/NIAD-827

NIAD-827: solving queue issues on AWS

---

Jenkinsfile

Add conditions for AWS deployment for 'main' branch only
https://gpitbjss.atlassian.net/browse/NIAD-857

NIAD-827: add-conditions-for-aws-deployment

---

Jenkinsfile

Fixed boolean variable syntax
NIAD-827

NIAD-827: Fixed boolean variable syntax

---

src/intTest/java/uk/nhs/digital/nhsconnect/lab/results/inbound/InboundUserAcceptanceTest.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/inbound/InboundMessageHandler.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/inbound/InboundMessageHandlerTest.java

Disable sending of recep messages, temporarily.
https://gpitbjss.atlassian.net/browse/NIAD-1063

NIAD-1063: temporarily disable nhsack

---

src/intTest/java/uk/nhs/digital/nhsconnect/lab/results/inbound/InboundMeshQueueTest.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/inbound/ChecksumService.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/inbound/InboundMessageHandler.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/outbound/queue/GpOutboundQueueService.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/utils/JmsHeaders.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/inbound/ChecksumServiceTest.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/inbound/InboundMessageHandlerTest.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/outbound/queue/GpOutboundQueueServiceTest.java

NIAD-1148: Create interchange message checksum

---

README.md
release/tests/send_message.sh

NIAD-860: Documentation updated

---

src/main/java/uk/nhs/digital/nhsconnect/lab/results/inbound/queue/MeshInboundQueueService.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/inbound/queue/UnknownWorkflowException.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/mesh/MeshService.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/mesh/http/MeshClient.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/mesh/message/WorkflowId.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/model/edifact/MessageType.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/inbound/queue/MeshInboundQueueServiceTest.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/mesh/MeshServiceTest.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/mesh/message/WorkflowIdTest.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/model/edifact/MessageTypeTest.java

Only Pathology and Screening message types are published to the inbound MESH queue.
https://gpitbjss.atlassian.net/browse/NIAD-998

NIAD-998: Only Pathology and Screening message types are published to the inbound MESH queue.

---

Jenkinsfile

Update Terraform Binary path to execute TF build using specific TF binary version.
https://gpitbjss.atlassian.net/browse/NIAD-1191

NIAD-1191: Update terraform path

---

src/intTest/resources/fhir/multi_pathology_msg1.fhir.json
src/intTest/resources/fhir/multi_pathology_msg2.fhir.json
src/intTest/resources/fhir/pathology.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_with_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_with_nhsack.2.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_with_nhsack.3.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_without_nhsack.1.fhir.json
src/main/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/ProcedureRequestMapper.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/ProcedureRequestMapperTest.java

Update "intent" property value to "order" for Procedure Request.
https://gpitbjss.atlassian.net/browse/NIAD-1179

NIAD-1179: Update "intent" property value to "order" for Procedure Request

---

src/intTest/resources/success_uat_data/NHS004/screening_multi_message_with_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_multi_message_with_nhsack.2.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_multi_message_with_nhsack.3.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_partial_acceptance_with_nhsack.1.fhir.json

Change values in acceptance test files to fix breaking tests

NIAD-0: fix acceptance test files

---

src/main/java/uk/nhs/digital/nhsconnect/lab/results/model/edifact/LaboratoryInvestigationResult.java
src/test/java/uk/nhs/digital/nhsconnect/lab/results/model/edifact/LaboratoryInvestigationResultTest.java

NIAD-1200: Measurement unit for 002 message type

---

mesh/mesh.sh
release/tests/README.md
release/tests/mesh_connectivity.py

NIAD-1237: MESH connectivity test tool

---

CHANGELOG.md
build.gradle
release/DOCKERHUB.md
release/version.sh

NIAD-1260: Release 0.0.3 into main

---

src/intTest/resources/fhir/multi_pathology_msg1.fhir.json
src/intTest/resources/fhir/multi_pathology_msg2.fhir.json
src/intTest/resources/fhir/multi_pathology_msg3.fhir.json
src/intTest/resources/fhir/pathology_2.fhir.json
src/intTest/resources/fhir/pathology_3.fhir.json
src/intTest/resources/fhir/screening.fhir.json
src/intTest/resources/success_uat_data/NHS002/full_acceptance_with_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS002/full_acceptance_with_nhsack.2.fhir.json
src/intTest/resources/success_uat_data/NHS002/full_acceptance_without_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_with_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_with_nhsack.2.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_with_nhsack.3.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_without_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_full_acceptance_with_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_full_acceptance_without_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_multi_message_with_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_multi_message_with_nhsack.2.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_multi_message_with_nhsack.3.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_partial_acceptance_with_nhsack.1.fhir.json

NIAD-1295: Reformatting json files to match intellij and vscode default formatting

---

src/intTest/java/uk/nhs/digital/nhsconnect/lab/results/IntegrationBaseTest.java
src/intTest/resources/fhir/multi_pathology_msg1.fhir.json
src/intTest/resources/fhir/multi_pathology_msg2.fhir.json
src/intTest/resources/fhir/multi_pathology_msg3.fhir.json
src/intTest/resources/fhir/pathology_2.fhir.json
src/intTest/resources/fhir/pathology_3.fhir.json
src/intTest/resources/fhir/screening.fhir.json
src/intTest/resources/success_uat_data/NHS002/full_acceptance_with_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS002/full_acceptance_with_nhsack.2.fhir.json
src/intTest/resources/success_uat_data/NHS002/full_acceptance_without_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_with_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_with_nhsack.2.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_with_nhsack.3.fhir.json
src/intTest/resources/success_uat_data/NHS003/full_acceptance_without_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_full_acceptance_with_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_full_acceptance_without_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_multi_message_with_nhsack.1.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_multi_message_with_nhsack.2.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_multi_message_with_nhsack.3.fhir.json
src/intTest/resources/success_uat_data/NHS004/screening_partial_acceptance_with_nhsack.1.fhir.json
src/main/java/uk/nhs/digital/nhsconnect/lab/results/model/FhirProfiles.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/DiagnosticReportMapper.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/FhirProfiles.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/MedicalReportMapper.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/ObservationMapper.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/OrganizationMapper.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/PatientMapper.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/PractitionerMapper.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/ProcedureRequestMapper.java
src/main/java/uk/nhs/digital/nhsconnect/lab/results/translator/mapper/SpecimenMapper.java

NIAD-1295: missing profile information

---

README.md

NIAD-1514: Documentation updated

---

CHANGELOG.md
build.gradle
release/DOCKERHUB.md
release/version.sh

Preparing pathology and screening release 0.0.5.
https://gpitbjss.atlassian.net/browse/NIAD-1570

NIAD-1570: Release 0.0.5

---

Jenkinsfile

NIAD-2056: remove-deployment-from-jenkins.

---

build.gradle

Updated Spring Boot to 2.15.13 and TestContainers to 1.16.1
https://gpitbjss.atlassian.net/browse/NIAD-2119

NIAD-2119: Security vulnerabilities upgraded

---

.github/workflows/pr-lint.yml
Jenkinsfile

NIAD-0000: Add 1hour timeout to Jenkins build

---

.github/workflows/pr-lint.yml

NIAD-3307: Changed pr naming rules for Dependabot.

---

.github/workflows/pr-lint.yml

Testing different Regex rules to pass PR name check when Dependabot PRs are automatically generated, as it is currently failing.
https://nhse-dsic.atlassian.net/browse/NIAD-3309

NIAD-3309: Update Regex to accept Dependabot PR names

---

.github/workflows/build.yml
scripts/create_build_id.sh

Brought build Id generation in line with the requesting adapter. The build ID generation was broken once merged into the main branch.
[NIAD-3152](https://nhse-dsic.atlassian.net/browse/NIAD-3195)

NIAD-3152: Brought build Id generation in line with the requesting adapter.

---

README.md
documentation/postman collection/pathology_postman_collection.json
documentation/postman collection/pathology_postman_environment.json

Added postman requests, and local environment to the documentation. This includes all known interactions, together with documentation for each interaction.
[NIAD-3311](https://nhse-dsic.atlassian.net/browse/NIAD-3311)

NIAD-3311: Added postman requests, and local environment to the documentation.

---

build.gradle

Updated Spring and keystore to fulfil dependabot's suggestions.
[NIAD-3312](https://nhse-dsic.atlassian.net/jira/software/c/projects/NIAD/boards/68?selectedIssue=NIAD-3312)

NIAD-3312: Updated Spring and keystore.

---

.github/workflows/release.yml

* Update publish folder configuration as I had incorrectly set it to the src folder, and not the root folder where the DOCKERFILE is contained.
NIAD-3394

NIAD-3394: Update publish folder configuration
